/** Общий UI-слой: два shell'а (telegram/desktop) на одном конфиге навигации + маршруты. */
export { PlatformProvider, usePlatform, detectPlatform, type Platform } from './PlatformProvider';
export { navItems, titleForPath, type NavItem, type NavId } from './navItems';
export { AppShell } from './AppShell';
export { TelegramShell } from './TelegramShell';
export { DesktopShell } from './DesktopShell';
export { Sidebar } from './Sidebar';
export { BottomNav } from './BottomNav';
export { TopBar } from './TopBar';
export { PageHeader } from './PageHeader';
export { SectionHeader } from './SectionHeader';
export { StatCard } from './StatCard';
export { GameCard } from './GameCard';
export { BalanceCard } from './BalanceCard';
export { RewardCard } from './RewardCard';
export { SettingRow } from './SettingRow';
export { EmptyState } from './EmptyState';
export { ShellDemo } from './ShellDemo';
export { useTelegramWebApp, haptic, getWebApp, isTelegramWebApp, type TelegramState } from './telegram';
export { GamesLobby } from './pages/GamesLobby';
export { ProfilePage } from './pages/ProfilePage';
export { BalancePage } from './pages/BalancePage';
export { RewardsPage } from './pages/RewardsPage';
export { SettingsPage } from './pages/SettingsPage';
